### ISSUE TITLE
How to get “libusb-1.0.lib” and “librtlsdr.lib" ?

### ISSUE THREAD

**Issue by DG2YCB** [jorgem-seq/ExtIO_RTL#1]
Hi, I am trying to build with Visual Studio, but I am getting errors because “libusb-1.0.lib” and “librtlsdr.lib" were not found. How or where can I get these two files? Do you have them?
Thanks

**Comment by jorgem-seq** [comment]
Answering to https://github.com/jorgem-seq/ExtIO_RTL/issues/1 and https://github.com/jorgem-seq/ExtIO_RTL/issues/2, the project file expects librtlsdr and libusb headers and static libraries to be placed in the search path:

https://github.com/jorgem-seq/ExtIO_RTL/blob/a0faace12552736c8535e4a2c95c0c895131598e/ExtIO_RTL_dll_vs2019.vcxproj#L62

https://github.com/jorgem-seq/ExtIO_RTL/blob/a0faace12552736c8535e4a2c95c0c895131598e/ExtIO_RTL_dll_vs2019.vcxproj#L72

The steps to compile those libraries are outside the scope of this project, anyways VS solutions to compile everything from sources are in https://github.com/jorgem-seq/librtlsdr-vs-project-files.

**Comment by jorgem-seq** [comment]
Closing issue due to repository archival.
