### ISSUE TITLE
Feature Request: Please add Auto-Q for freq < 24.5 MHz

### ISSUE THREAD

**Issue by DG2YCB** [jorgem-seq/ExtIO_RTL#3]
Hi, it would be very useful if you could add the following option: Auto-Q. With Auto Q enabled let the RTL stick automatically switch to Q channel when a frequency below 24.5 MHz is selected, and back to Direct sampling disabled when set to any frequency abot 24.5 MHz. Please be so kind as to add this feature.

**Comment by jorgem-seq** [comment]
Testing release with new options: https://github.com/jorgem-seq/ExtIO_RTL/releases/tag/v20211100
Branch switch is set to 14.4 MHz (Xtal/2) for convenience.

**Comment by DG2YCB** [comment]
Yes it works!! Thanks a lot, Jorge! Great improvement!

**Comment by DG2YCB** [comment]
I tried to compile your new source code from the testing branch, but I am getting one error. "Not resolved external symbol "_rtlsdr_set_bias_tee". I didn't get this error with your version without Auto Q (from master branch). Any idea how I can bring it to work?

**Comment by jorgem-seq** [comment]
Thank you @DG2YCB  for testing, I appreciate it.
For problems with external libraries or headers the answer is exactly the same as in https://github.com/jorgem-seq/ExtIO_RTL/issues/1.

**Comment by DG2YCB** [comment]
One observation: Sometimes with your new DLL when using Q auto, HDSDR seems to have some troubles when switching from one band to another. Instead of the last used frequency (by band) HDSDR starts with any other, which sometimes is even outside the band segment, so that band zoom doesn't work properly anymore. To me, it looks as if it has something to do with the new auto Q feature. Any idea what could cause it?

**Comment by jorgem-seq** [comment]
Closing issue due to repository archival.
